CREATE OR REPLACE TRIGGER STOA
AFTER INSERT
ON ALUMNI
FOR EACH ROW
DECLARE
R Student%ROWTYPE;
BEGIN
SELECT * INTO R FROM student s WHERE s.STUdENT_ID=:new.sTUDENT_ID;
DECLARE CURSOR CRS IS SELECT * FROM STUDENT_RESEARCH WHERE STUDEnT_ID=:new.STUDENT_iD;
X CRS%ROWTYPE;
begin
OPEN CRS;
LOOP FETCH CRS INTO X;
EXIT WHEN CRS%NOTFOUND;

INSERT INTO ALUMNI_RESEARCH VALUES (X.STUDENT_ID, X.RESEArCH_ID);
END LOOP;
CLOSE CRS;
DELETE FROM Student WHERE StUdent_id =R.StudEnt_ID;
END;
end;

CREATE OR REPLACE TRIGGER CONFERENCE_DATE
BEFORE INSERT ON CONFERENCE 
FOR EACH ROW
BEGIN 
  IF(:NEW.START_DATE < :NEW.END_DATE) THEN
  RAISE_APPLICATION_ERROR(-20001,'DATE NOT VALID' );
  END IF;
exception
  when others then
    dbms_output.put_line('VALUE INSERTED');
END;
