CREATE OR REPLACE VIEW User_Info_View ("ACC_ID" , "NAME", "PHONE_NUMBER" , "EMAIL" ,"PASSWORD", "DEPARTMENT", "RESEARCH_INTEREST" , "NUMBER_OF_RESEARCHES", "ATTENDED_CONFERENCE" ) AS select ACC_ID ,NAME, u.contact.phone_number , u.contact.email ,PASSWORD,DEPARTMENT,RESEARCH_INTEREST,NUMBER_OF_RESEARCHES,ATTENDED_CONFERENCE from users u

CREATE OR REPLACE VIEW RESEARCH_VIEW ("RESEARCH_ID","APPROVE_STATUS","PAPER_PDF","PAPER_LINK","PUBLISHER","PAPER_TITLE","PUBLISH_STATUS","PAPER_ABSTRACT","PAPER_TYPE") AS (SELECT * FROM RESEARCH)

CREATE OR REPLACE VIEW RESEARCH_VIEW ("RESEARCH_ID","APPROVE_STATUS","PAPER_PDF","PAPER_LINK","PUBLISHER","PAPER_TITLE","PUBLISH_STATUS","PAPER_ABSTRACT","PAPER_TYPE") AS (SELECT * FROM RESEARCH WHERE PAPER_TITLE LIKE '%Writing%')

